package DBpra2::Model::Model1;

use strict;
use base 'Catalyst::Model::DBIC::Schema';
use utf8;

__PACKAGE__->config(
    schema_class => 'Schema1',
);

=head1 NAME

DBpra2::Model::Model1 - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<DBpra2>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Schema1>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
